# -*- coding: utf-8 -*-
"""Chat_Bot_Text_And_Visual_Q/A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7E5cxBT_hYhoZoDzH4Dnq1uxwlQRHA8
"""

from transformers import pipeline

pip install SpeechRecognition

import speech_recognition as sr

model=sr.Recognizer()

pip install pydub

mp3_file=r'/content/class.mp3'
from pydub import AudioSegment
from pydub.playback import play
audio=AudioSegment.from_file(mp3_file)
audio.export("classw.wav",format="wav")

audio_file=r'/content/classw.wav'
with sr.AudioFile(audio_file) as source:
  audio_data=model.record(source)
  text=model.recognize_google(audio_data)
  print(text)

summarize=pipeline("summarization")

text=input('')

result=summarize(text)

result

analyzer=pipeline('sentiment-analysis')

text_input=input('enter some  text:')

result=analyzer(text_input)

result

from transformers import pipeline

# Load a pre-trained question-answering pipeline from Hugging Face
qa_pipeline = pipeline("question-answering")

# Function to ask questions and get answers based on the provided context
def ask_user_questions():
    # Default context
    context = '''summary_text': "Recursion is just another way to create a loop but infinite Loops aren't very useful in practice .
    Recursive functions are not the right choice in every situation but they are very good for tree and graph traversals .
     In the next video I'll explain how to improve this with memoization .'''

   # print("Welcome to the interactive story! Ask me any question about Luca's adventure.")

    # Loop to continuously take user questions
    while True:
        # Ask the user to input a question
        user_question = input("Ask a question (or type 'exit' to quit): ").lower()

        # Exit condition
        if user_question == 'exit':
            print("Goodbye!")
            break

        # Use the pipeline to get the answer from the model
        result = qa_pipeline(question=user_question, context=context)

        # Print the answer
        print("Answer:", result['answer'])

        # Ask if the user wants to ask another question
        continue_choice = input("Do you want to ask another question? (yes/no): ").lower()
        if continue_choice != 'yes':
          print("Goodbye!")
          # Corrected indentation for the break statement
          break  # Exit if the user does not want to continue

# Start the question-answering loop
ask_user_questions()

vqa_pipeline = pipeline("visual-question-answering")

img=r'/content/133898006337294417.jpg'

ques=input('enter the question:')
res=vqa_pipeline(image=img,question=ques)
print(res)

ques=input('enter the question:')
res=vqa_pipeline(image=img,question=ques)
print(res)